/*
 * Gareth's Beer API
 *
 * A simple demonstration API exposing operations for working with Beers
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/",
		Index,
	},

	Route{
		"Addbeer",
		strings.ToUpper("Post"),
		"/api/beers",
		Addbeer,
	},

	Route{
		"Deletebeer",
		strings.ToUpper("Delete"),
		"/api/beers/{id}",
		Deletebeer,
	},

	Route{
		"FindbeerById",
		strings.ToUpper("Get"),
		"/api/beers/{id}",
		FindbeerById,
	},

	Route{
		"Findbeers",
		strings.ToUpper("Get"),
		"/api/beers",
		Findbeers,
	},
}
